version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./.docker/create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  pg_data:
